name: inchi-identity-api

channels:
  - conda-forge

dependencies:
  - python=3.12
  - rdkit
  - numpy
  - pandas
  - requests
  - openpyxl
  - python-dotenv
  - flask
  - flask-cors
  - pillow
  - pip
  - pip:
      - py3Dmol
      - pytest
      - inchi-identity